/**
 * Developer dashboard page
 * Generated by create_structure.sh
 * TODO: Implement this component
 */

import React from 'react';

const developer = () => {
    return (
        <div>
            <h2>developer</h2>
            <p>TODO: Implement Developer dashboard page</p>
        </div>
    );
};

export default developer;
