/**
 * Main web interface page
 * Generated by create_structure.sh
 * TODO: Implement this component
 */

import React from 'react';

const index = () => {
    return (
        <div>
            <h2>index</h2>
            <p>TODO: Implement Main web interface page</p>
        </div>
    );
};

export default index;
