/**
 * Research tools page
 * Generated by create_structure.sh
 * TODO: Implement this component
 */

import React from 'react';

const research = () => {
    return (
        <div>
            <h2>research</h2>
            <p>TODO: Implement Research tools page</p>
        </div>
    );
};

export default research;
